#!/bin/bash

# To always authenticate when accessing a host, run this:
#   ./always-auth HOST

set -e

if (($# != 1)); then
  echo >&2 "usage: $0 host"
  exit 1
fi

h="$1"
case "$h" in
*.googlesource.com) : ;;
*.*)
  echo >&2 "error: invalid host $h"
  echo >&2 "       expected host or host.googlesource.com"
  exit 1
  ;;
*) h=$h.googlesource.com ;;
esac

git config --global "url.https://$h/a/.insteadof" "https://$h/"
