#!/bin/bash

p=0
h=0

while read n; do
  case "$n" in
  protocol=https) p=1;;
  host=*.googlesource.com) h=1;;
  '') break;;
  esac
done

if ((p && h && get == "$1")); then
  A=http://metadata/0.1/meta-data/service-accounts/default/acquire
  S=https://www.googleapis.com/auth/gerritcodereview
  p=$(curl -s "$A?scopes=$S" |
      python -c 'import json,sys;print json.load(sys.stdin)["accessToken"]')
  echo username=git
  echo "password=$p"
  echo
fi
