#!/bin/sh

# Installs git-credential-serviceaccount by writing to ~/.gitconfig.

set -e
s=$(which "$0")
d=$(dirname "$s")
d=$(cd "$d" && pwd)

v=credential.helper
p="$d/git-credential-serviceaccount"

echo -n "Adding $v to ~/.gitconfig ... "
git config --global --add $v "$p"
echo done.

echo "       $v is now:"
git config --global --get-all $v | sed 's/^/  /'

echo
echo "git version must be >= 1.7.9:"
git version
echo
